### ISSUE TITLE
Setting proxy in eunomia-base doesn't work for git

### ISSUE THREAD

**Issue by sbar95** [KohlsTechnology/eunomia#154]
**What version of eunomia are you using?**

eunomia version: v0.0.3

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

n/a

**What did you do?**

In my environment I need to use proxy. I set such GitOpsConfig:
```
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: hello-world-yaml
spec:
  templateSource:
    uri: https://github.com/KohlsTechnology/eunomia
    ref: master
    contextDir: examples/hello-world-yaml/template1
    httpProxy: http://my-proxy.com:my-port
    httpsProxy: http://my-proxy.com:my-port
  parameterSource:
    ref: master
    contextDir: examples/hello-world-yaml/parameters
    httpProxy: http://my-proxy.com:my-port
    httpsProxy: http://my-proxy.com:my-port
  triggers:
  - type: Change
  #- type: Periodic
    #cron: '*/1 * * * *'
  serviceAccountRef: eunomia-runner-yaml
  templateProcessorImage: docker-registry.default.svc:5000/my-namespace/eunomia-base:latest
  resourceHandlingMode: CreateOrMerge
  resourceDeletionMode: Delete
```
I create a proper namespace and service account. Then I apply the above GitOpsConfig.

**What did you expect to see?**

![image](https://user-images.githubusercontent.com/44879339/68848822-41cb5e80-06d1-11ea-91a7-23f40898c18e.png)

**What did you see instead?**

![image](https://user-images.githubusercontent.com/44879339/68848317-683cca00-06d0-11ea-940e-3e00270941e2.png)

**Solution**

This line
https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/base/bin/gitClone.sh#L47
should be
`git clone -c "http.proxy=$TEMPLATE_GIT_HTTP_PROXY" -b $TEMPLATE_GIT_REF $TEMPLATE_GIT_URI $TEMPLATE_GIT_DIR`

And this line
https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/base/bin/gitClone.sh#L77
should be
`git clone -c "http.proxy=$PARAMETER_GIT_HTTP_PROXY" -b $PARAMETER_GIT_REF $PARAMETER_GIT_URI $PARAMETER_GIT_DIR`
