### ISSUE TITLE
gitClone.sh: errors copying .gitconfig file

### ISSUE THREAD

**Issue by tomsucho** [KohlsTechnology/eunomia#173]
**What version of eunomia are you using?**

eunomia version:
v0.0.4
for the container which runs the gitClone.sh script I tried:
quay.io/kohlstechnology/eunomia-base:v0.0.4
quay.io/kohlstechnology/eunomia-base:latest
in both cases result was the same error.

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
Tried to integrate Eunomia with my test git repo for the first time. Created a secret from the file .gitconfig that contains git configuration with user & password for accessing my test repo:
```
(python3) $ kubectl create secret generic template-gitconfig --from-file=.gitconfig -n gcp-prj-demo1
secret/template-gitconfig created
(python3) $ kubectl create secret generic parameter-gitconfig --from-file=.gitconfig -n gcp-prj-demo1
secret/parameter-gitconfig created
```

Then deployed the  GitOpsConfig CRD pointing to the test repo and the credentials:
```
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: gitops-testing
spec:
  templateSource:
    uri: https://github.com/tomsucho/gitops-testing
    ref: master
    contextDir: templates/gcp-project
    secretRef: template-gitconfig
  parameterSource:
    ref: master
    contextDir: test_vars/gcp_project
    secretRef: parameter-gitconfig
  triggers:
  - type: Change
  #- type: Periodic
    #cron: '*/1 * * * *'
  serviceAccountRef: eunomia-runner-yaml
  templateProcessorImage: quay.io/kohlstechnology/eunomia-base:latest
  resourceHandlingMode: CreateOrMerge
  resourceDeletionMode: Delete
```

**What did you expect to see?**
A container starting and picking up the .gitconfig, then fetching my master branch repo and then running template processor against template dir, which would in turn configure the generated resources in the cluster.

**What did you see instead?**
1. On first attempt got the below error in container logs, indicating that gitClone.sh most likely doesn't see the hidden .gitconfig file mounted under /template-gitconfig/  
```
$ kubectl logs gitopsconfig-gitops-testing-qx8mml-ppd8d -n gcp-prj-demo1
+ whoami
+ '[' -w /etc/passwd ']'
++ id -u
++ id -g
+ echo 'gitopsjob:x:1001:0:gitopsjob user:/tmp:/sbin/nologin'
+ exec wrapper.sh
+ export HOME=/tmp
+ HOME=/tmp
+ /usr/local/bin/gitClone.sh
+ echo Cloning Repositories
+ pullFromTemplatesRepo
+ set +u
+ '[' '' ']'
+ '[' '' ']'
+ '[' '' ']'
+ '[' /template-gitconfig ']'
+ '[' -d /template-gitconfig ']'
+ for file in "$TEMPLATE_GITCONFIG"/*
++ basename '/template-gitconfig/*'
Cloning Repositories
+ cp -f '/template-gitconfig/*' '~/*'
cp: cannot stat '/template-gitconfig/*': No such file or directory
```
2. On 2nd attempt I changed the secret from .gitconfig to just gitconfig to check if the file will be seen at least the mount location and it was indeed however then the copy to home dir failed:
```
$ kubectl logs gitopsconfig-gitops-testing-om5bep-hzjxv -n gcp-prj-demo1

+ whoami
+ '[' -w /etc/passwd ']'
++ id -u
++ id -g
+ echo 'gitopsjob:x:1001:0:gitopsjob user:/tmp:/sbin/nologin'
+ exec wrapper.sh
+ export HOME=/tmp
+ HOME=/tmp
+ /usr/local/bin/gitClone.sh
+ echo Cloning Repositories
+ pullFromTemplatesRepo
+ set +u
+ '[' '' ']'
+ '[' '' ']'
+ '[' '' ']'
+ '[' /template-gitconfig ']'
+ '[' -d /template-gitconfig ']'
+ for file in "$TEMPLATE_GITCONFIG"/*
++ basename /template-gitconfig/gitconfig
Cloning Repositories
+ cp -f /template-gitconfig/gitconfig '~/gitconfig'
cp: cannot create regular file '~/gitconfig': No such file or directory
```
