### ISSUE TITLE
Please add a health-check for /webhook/ URI

### ISSUE THREAD

**Issue by tomsucho** [KohlsTechnology/eunomia#180]
**Is your feature request related to a problem? Please describe.**
Google’s Load Balancer performs health checks on the associated backend service. The service must return a status of 200. If it does not, the load balancer marks the instance as unhealthy and does not send it any traffic until the health check shows that it is healthy again.
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress

**Describe the solution you'd like**
A health-check implemented which would return status for GET /webhook/ instead of just 404

**Describe alternatives you've considered**
I tried to change manually the health-check GCP HTTPS LB uses, to just send a TCP port probe, but it keeps reverting back to HTTP "/" after a while and thus the service becomes unavailable. 

**What version of eunomia are you using?**
eunomia version:
v0.0.4
**Additional context**

**Comment by Smiley73** [comment]
Do we need a separate health check for the /webhook/health or would a /health better

**Comment by tomsucho** [comment]
Read in GCP docs that actually LB should pick up a readinessProbe configured on the pod, tried it but it didn’t work.. maybe because this wasn’t http type probe but just tcp:
```
      containers:
        - name: eunomia-operator
          image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8383
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
```
Also the pod has actually two ports and when I added two readinessProbe only the last one was actually configured which would imply you can have only one per pod.. so in light of that I think one /health type http per whole pod... or maybe even to be on safe side return status 200 OK also on GET "/" (in case GCP LB doesn't pick up the readinessProbe path - there were issues around that e.g.: https://github.com/kubernetes/ingress-gce/issues/241)
