### ISSUE TITLE
Automatically clean up old Jobs

### ISSUE THREAD

**Issue by akavel** [KohlsTechnology/eunomia#196]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when there is increasing number of old Jobs littering the cluster, created by eunomia for each trigger.

**Describe the solution you'd like**

It would be great if eunomia deleted old completed Jobs, e.g. in a similar way as a CronJob does, where it can be [configured as below](https://stackoverflow.com/a/55075758), through `failedJobsHistoryLimit` and `successfulJobsHistoryLimit` options:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  schedule: "*/10 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
         ...
```

For "Periodic" trigger, the values of those options could probably be passed straight from a GitOpsConfig CR to the CronJob, to be rendered as in the example above.

**Describe alternatives you've considered**

none really

**What version of eunomia are you using?**

eunomia version: 0.0.4

**Additional context**

Thanks to @tomsucho for the original report!
