### ISSUE TITLE
Base Template Processor Fails To Apply 'contextDir' With Zero YAML Files

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#276]
**What version of eunomia are you using?**

eunomia version: v0.1.1

**Does this issue reproduce with the latest release?**
Yes.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
OCP v3.11
</pre></details>

**What did you do?**
I applied a simple GitOpsConifg CR to my OpenShift 3.11 cluster. The `contextDir` did not contain any YAML files.

Example GitOpConfig CR ...
```
---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: namespace-poc
spec:
  templateSource:
    uri: https://github.example.com/operations/openshift-namespaces
    ref: bug-tester
    contextDir: mycluster/namespaces
    secretRef: eunomia-runner-github
  triggers:
  - type: Webhook
  serviceAccountRef: eunomia-runner
  templateProcessorImage: docker-registry.default.svc:5000/default/eunomia-base:latest
  resourceHandlingMode: Apply
  resourceDeletionMode: Delete
```

**What did you expect to see?**
I expect the eunomia base template processor image to be able to successfully apply a `contextDir` that contains zero YAML files.

**What did you see instead?**
The base template process fails with the below error ...
```
+ echo export SERVICE_CA_BUNDLE=
+ getNamespace
++ cat /var/run/secrets/kubernetes.io/serviceaccount/namespace
+ echo export NAMESPACE=xpaas-eunomia
+ source /tmp/envs.sh
++ export CA_BUNDLE=
++ CA_BUNDLE=
++ export SERVICE_CA_BUNDLE=
++ SERVICE_CA_BUNDLE=
++ export NAMESPACE=xpaas-eunomia
++ NAMESPACE=xpaas-eunomia
+ /usr/local/bin/processParameters.sh
+ echo 'Processing Parameters'
+ FOLDERS=
+ '[' -e /git/parameters/./hierarchy.lst ']'
+ FOLDERS=/git/parameters/.
+ '[' -n /git/parameters/. ']'
+ VALUES_FILE=/tmp/eunomia_values_processed1.yaml
+ echo ---
Processing Parameters
+ for DIR in ${FOLDERS}
+ echo 'Processing files in /git/parameters/.'
Processing files in /git/parameters/.
++ find /git/parameters/. -maxdepth 1 -name '*.json' -o -name '*.yaml' -o -name '*.yml'
+ YAML_FILES=/git/parameters/./cr.yaml
+ '[' '!' -z /git/parameters/./cr.yaml ']'
+ goyq merge -i -x /tmp/eunomia_values_processed1.yaml /git/parameters/./cr.yaml
+ '[' -e /tmp/eunomia_values_processed1.yaml ']'
+ envsubst
+ /usr/local/bin/processTemplates.sh
Processing Templates
+ echo Processing Templates
+ cp -R '/git/templates/mycluster/namespaces/*' /git/manifests/
cp: cannot stat '/git/templates/mycluster/namespaces/*': No such file or directory
```
