### ISSUE TITLE
Failure To Create Namespace Using Base Template Processor

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#277]
**What version of eunomia are you using?**

eunomia version: v0.1.1

**Does this issue reproduce with the latest release?**
Yes.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
OCP 3.11
</pre></details>

**What did you do?**
Tried to use the base template processor to create a namespace, quota, limit range, and role binding.

GitOpsConfig CR ...
```
---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: namespace-poc
spec:
  templateSource:
    uri: https://github.example.com/operations/openshift-namespaces
    ref: bug-tester
    contextDir: mycluster/namespaces
    secretRef: eunomia-runner-github
  triggers:
  - type: Webhook
  serviceAccountRef: eunomia-runner
  templateProcessorImage: docker-registry.default.svc:5000/default/eunomia-base:latest
  resourceHandlingMode: Apply
  resourceDeletionMode: Delete
```

This is the YAML file from the `contextDir` ...
```
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "discover all the eunomia bugs"
    openshift.io/display-name: bug-tester
  labels:
    app-name: eunomia
    billing-dept-id: "1234"
    environment-name: dev-a
    environment-type: platform
    lob: paas
    network-policy-source: None
    program-id: None
  name: bug-tester
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: LimitRange
metadata:
  name: compute
  namespace: bug-tester
spec:
  limits:
    - type: Pod
      max:
        cpu: "4"
        memory: "16Gi"
      min:
        cpu: "10m"
        memory: "100Mi"
    - type: Container
      max:
        cpu: "4"
        memory: "16Gi"
      min:
        cpu: "10m"
        memory: "100Mi"
      default:
        cpu: "100m"
        memory: "100Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: bug-tester
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 16Gi
    limits.cpu: "4"
    limits.memory: 16Gi
---
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: admins
    namespace: bug-tester
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: Namespace-Admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: OpenShift-L2
kind: List
```

**What did you expect to see?**
I expected the Job pod created by eunomia to finish successfully without an errors.

**What did you see instead?**
The namespace, quota, limit range, and role binding were successfully created. But ... the k8s Job created by the eunomia operator failed with the error message `error: the server doesn't have a resource type "Status"`. See attached file for full log.

[junk.txt](https://github.com/KohlsTechnology/eunomia/files/4136173/junk.txt)
