### ISSUE TITLE
Removing Periodic trigger does not delete the cronjob

### ISSUE THREAD

**Issue by vinny-sabatini** [KohlsTechnology/eunomia#279]
**What version of eunomia are you using?**

eunomia version: v0.1.1

**Does this issue reproduce with the latest release?**

Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
OCP 3.11
</pre></details>

**What did you do?**

I created a GitOpsConfig with only a `Webhook` trigger. I then added a `Periodic` trigger to the GitOpsConfig. The CronJob was created, and then I removed the `Periodic` trigger from the GitOpsConfig.

Example GitOpsConfig:
```
---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: namespace-poc
spec:
  templateSource:
    uri: https://github.example.com/Operations/openshift-namespaces
    ref: master
    contextDir: namespaces
    secretRef: eunomia-runner-github
  triggers:
  - type: Webhook
  - type: Periodic
    cron: "0 * * * *"
  serviceAccountRef: eunomia-runner
  templateProcessorImage: docker-registry.default.svc:5000/k-images/eunomia-base:latest
  resourceHandlingMode: Apply
  resourceDeletionMode: Delete
```

**What did you expect to see?**

The Kubernetes CronJob to be deleted for the GitOpsConfig.

**What did you see instead?**

The Kubernetes CronJob was not deleted.
The CronJob was not deleted upon restarting the Eunomia Operator.
