### ISSUE TITLE
Setting resourceDeletionMode to None Prevents Applying Resources

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#311]
**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version: v0.1.4

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
OCP v3.11
</pre></details>

**What did you do?**
I created a GitOpsConfig with the `resourceDeletionMode` set to `None.
```
---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: namespace-poc
spec:
  templateSource:
    uri: https://github.example.com/Operations/namespaces
    ref: master
    contextDir: foo/namespaces
    secretRef: eunomia-runner-github
  triggers:
  - type: Webhook
  serviceAccountRef: eunomia-runner
  templateProcessorImage: docker-registry.default.svc:5000/images/eunomia-base:latest
  resourceHandlingMode: Apply
  resourceDeletionMode: None
```

**What did you expect to see?**
I expected that new a modified resource should be applied using this GitOpsConfig.

**What did you see instead?**
The `kubectl apply` command is not run in the k8s `Job` created by Eunomia. The `Job` logs from the base template processor show the below message ...

```
+ echo 'Processing Parameters'
--
  | + FOLDERS=
  | Processing Parameters
  | + '[' -e /git/parameters/./hierarchy.lst ']'
  | + FOLDERS=/git/parameters/.
  | + '[' -n /git/parameters/. ']'
  | + VALUES_FILE=/tmp/eunomia_values_processed1.yaml
  | + echo ---
  | + for DIR in ${FOLDERS}
  | Processing files in /git/parameters/.
  | + echo 'Processing files in /git/parameters/.'
  | ++ find /git/parameters/. -maxdepth 1 -name '*.json' -o -name '*.yaml' -o -name '*.yml'
  | + YAML_FILES=/git/parameters/./cr.yaml
  | + '[' /git/parameters/./cr.yaml ']'
  | + goyq merge -i -x /tmp/eunomia_values_processed1.yaml /git/parameters/./cr.yaml
  | + '[' -e /tmp/eunomia_values_processed1.yaml ']'
  | + envsubst
  | + /usr/local/bin/processTemplates.sh
  | + echo Processing Templates
  | + cp -R /git/templates/foo/namespaces/. /git/manifests/
  | Processing Templates
  | + /usr/local/bin/resourceManager.sh
  | + TAG_OWNER=gitopsconfig.eunomia.kohls.io/owner
  | + TAG_APPLIED=gitopsconfig.eunomia.kohls.io/applied
  | + '[' Apply == None ']'
  | + '[' None == None ']'
  | + echo 'CREATE_MODE and/or DELETE_MODE is set to None; This means that the template processor already applied the resources. Skipping the Manage Resources step.'
  | + exit 0
  | CREATE_MODE and/or DELETE_MODE is set to None; This means that the template processor already applied the resources. Skipping the Manage Resources step.
```
